version: '3.9'
services:
  api:
    build: .
    container_name: projetoteste-api
    restart: always
    environment:
      ENV: 'develop'
      APP_BIND_ADDR: 0.0.0.0
      APP_DIR: '/app'
      APP_MODULE_NAME: 'main'
      APP_NAME: 'app'
      APP_PORT: 5000
      DB_HOST: 'postgres'
      DB_NAME: 'projetoTesteDB'
      DB_PASSWORD: "root"
      DB_PORT: 5432
      DB_PROTOCOL: 'postgresql'
      DB_USER: 'postgres'
      JWT_ALGORITHM: 'HS256'
      JWT_EXPIRE_TIME: 60
      JWT_SECRET: '###'

    ports:
      - 5000:5000
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: projetoTesteDB
    ports:
      - 27017:27017
    volumes:
      - ~/estudamais-db_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: rootbasicauth
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongodb
